/**
 * The JS port of EWDI's scoring against outputs of EWDI's own Python
 * functions (tests/fixtures/ewdi-golden.json, generated by running
 * app/risk/anomaly.py, app/features/compute.py and the numpy core of
 * app/ingest/embed.py on fixed inputs with EWDI's constants).
 */
const golden = require('../fixtures/ewdi-golden.json');
const {
  robustZ, slope, scoreWindow, levelsFromPercentiles, classify, buildFeatures,
} = require('../../services/earlyWarning/scoring');
const { greedyCluster } = require('../../services/earlyWarning/clustering');

const C = golden.constants;
const EWDI_CFG = {
  directions: C.DIRECTIONS,
  slopes: C.SLOPES,
  relFloor: C.REL_FLOOR,
  absFloor: C.ABS_FLOOR,
  clip: C.Z_CLIP,
  topK: C.TOP_K,
};
const close = (a, b, digits = 9) => expect(a).toBeCloseTo(b, digits);

describe('robust_z', () => {
  it.each(golden.robust_z.map((c) => [c.in, c.out]))('robust_z(%j) = %d', (input, expected) => {
    close(robustZ(input[0], input[1], input[2], { relFloor: C.REL_FLOOR, absFloor: C.ABS_FLOOR, clip: C.Z_CLIP }), expected);
  });
});

describe('slope (np.polyfit degree 1)', () => {
  it.each(golden.slope.map((c) => [c.in, c.out]))('slope(%j) = %d', (input, expected) => {
    close(slope(input), expected);
  });
});

describe('score_window', () => {
  it.each(Object.entries(golden.score_window))('%s', (name, { in: f, out }) => {
    const mine = scoreWindow(f, EWDI_CFG);
    close(mine.anomalyZ, out.anomaly_z);
    close(mine.score, out.score);
    expect(mine.attribution.map((a) => a.feature)).toEqual(out.attribution.map((a) => a.feature));
    mine.attribution.forEach((a, i) => {
      close(a.z, out.attribution[i].z, 6);
      close(a.share, out.attribution[i].share, 6);
    });
  });
});

describe('levels from percentiles, and classify', () => {
  it('matches numpy percentile (linear interpolation)', () => {
    const th = levelsFromPercentiles(golden.levels.scores, C.LEVEL_PERCENTILES);
    Object.entries(golden.levels.thresholds).forEach(([level, v]) => close(th[level], v, 12));
    const small = levelsFromPercentiles(golden.levels_small.scores, C.LEVEL_PERCENTILES);
    Object.entries(golden.levels_small.thresholds).forEach(([level, v]) => close(small[level], v, 12));
  });

  it.each(golden.levels.classified)('classify(%d) = %s', (score, level) => {
    expect(classify(score, golden.levels.thresholds)).toBe(level);
  });
});

describe('build_features', () => {
  const metrics = C.METRICS.map((name) => (C.COUNT_METRICS.includes(name)
    ? { name, kind: 'count' }
    : { name, kind: 'rate', gate: 'n_records', min: C.MIN_DAILY_RECORDS }));
  const cfg = {
    metrics,
    slopes: [
      { name: 'volume_slope', metric: 'n_records' },
      { name: 'sent_slope', metric: 'mean_sent', nullIfEmpty: true },
      { name: 'no_response_slope', metric: 'pct_no_response' },
    ],
    windowDays: C.WINDOW_DAYS,
    baselineDays: C.BASELINE_DAYS,
    enriched: C.ENRICHED,
  };

  it.each(Object.entries(golden.build_features.windows))('window ending %s', (windowEnd, expected) => {
    const mine = buildFeatures(golden.build_features.days, windowEnd, cfg);
    if (expected === null) {
      expect(mine).toBeNull();
      return;
    }
    expect(Object.keys(mine).sort()).toEqual(Object.keys(expected).sort());
    Object.entries(expected).forEach(([key, value]) => {
      if (value === null || typeof value === 'boolean') expect(mine[key]).toBe(value);
      else close(mine[key], value, 9);
    });
  });
});

describe('cluster (greedy cosine, tau 0.75)', () => {
  it('produces the same assignment, counts, kept clusters and centroids', () => {
    const { vectors, min_cluster: minCluster, tau, out } = golden.cluster;
    const mine = greedyCluster(vectors, { tau, minCluster });
    expect(mine.assign).toEqual(out.assign);
    expect(mine.counts).toEqual(out.counts);
    expect(mine.keep).toEqual(out.keep);
    // numpy works in float32 here; agree to ~6 digits.
    mine.centroids.forEach((c, k) => c.forEach((x, d) => expect(x).toBeCloseTo(out.centroids[k][d], 5)));
  });
});
